version: '3'

tasks:

  build:
    desc: Build the project.
    cmds:
      - go build -ldflags "-s -w" -o ac main.go

  dw:
    desc: Downloads the contest.
    deps: [build]
    silent: true
    cmds:
      - ./ac dw -c {{.CLI_ARGS}}
      
  lint:
    desc: "Lint golang code"
    cmds:
      - echo "Running golangci-lint..."
      - golangci-lint run --timeout=5m
      
  test:
    desc: "Run go tests verbosly"
    silent: true
    cmds:
      - echo "Running go tests via go test -v ./..."
      - go test -v ./...
